version: 2
workflows:
  version: 2
  tests:
    jobs: &workflow_jobs
      - node4:
          filters:
            tags:
              only: /.*/
      - node6:
          filters:
            tags:
              only: /.*/
      - node8:
          filters:
            tags:
              only: /.*/
      - node9:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - node4
            - node6
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - docs:
          requires:
            - node4
            - node6
            - node8
            - node9
          filters:
            tags:
              only: /.*/
      - sample_tests:
          requires:
            - lint
            - docs
          filters:
            branches:
              only:
                - master
                - repo-preparation
            tags:
              only: '/^v[\d.]+$/'
      - publish_npm:
          requires:
            - sample_tests
          filters:
            branches:
              ignore: /.*/
            tags:
              only: '/^v[\d.]+$/'
  nightly:
    triggers:
      - schedule:
          cron: 0 7 * * *
          filters:
            branches:
              only: master
    jobs: *workflow_jobs
jobs:
  node4:
    docker:
      - image: 'node:4@sha256:36adaf7ae6d88589009b54b1fef7a660768db5ec8248e82944604c07455d46ba'
        user: node
    steps: &unit_tests_steps
      - checkout
      - run: &remove_package_lock
          name: Remove package-lock.json if needed.
          command: |
            WORKFLOW_NAME=`python .circleci/get_workflow_name.py`
            echo "Workflow name: $WORKFLOW_NAME"
            if [ "$WORKFLOW_NAME" = "nightly" ]; then
              echo "Nightly build detected, removing package-lock.json."
              rm -f package-lock.json samples/package-lock.json
            else
              echo "Not a nightly build, skipping this step."
            fi
      - run:
          name: Install modules and dependencies.
          command: |-
            npm install
            repo_tools="node_modules/@google-cloud/nodejs-repo-tools/bin/tools"
            if ! test -x "$repo_tools"; then
              chmod +x "$repo_tools"
            fi
      - run:
          name: Run unit tests.
          command: npm test
      - run:
          name: Submit coverage data to codecov.
          command: node_modules/.bin/codecov
          when: always
  node6:
    docker:
      - image: 'node:6@sha256:d317acbe49df83929ff0c51f18c29a2aa470a172c2d72653bf266a2822578301'
        user: node
    steps: *unit_tests_steps
  node8:
    docker:
      - image: 'node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5'
        user: node
    steps: *unit_tests_steps
  node9:
    docker:
      - image: 'node:9@sha256:151c8b8a2f1b91a2b4b6cdb122ebf2c6c54809bf750b8ed050b7efdf236a6420'
        user: node
    steps: *unit_tests_steps
  lint:
    docker:
      - image: 'node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5'
        user: node
    steps:
      - checkout
      - run: *remove_package_lock
      - run:
          name: Install modules and dependencies.
          command: |
            mkdir -p /home/node/.npm-global
            npm install
            repo_tools="node_modules/@google-cloud/nodejs-repo-tools/bin/tools"
            if ! test -x "$repo_tools"; then
              chmod +x "$repo_tools"
            fi
            npm link
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Link the module being tested to the samples.
          command: |
            cd samples/
            npm link dialogflow
            npm install
            cd ..
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Run linting.
          command: npm run lint
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
  docs:
    docker:
      - image: 'node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5'
        user: node
    steps:
      - checkout
      - run: *remove_package_lock
      - run:
          name: Install modules and dependencies.
          command: |-
            npm install
            repo_tools="node_modules/@google-cloud/nodejs-repo-tools/bin/tools"
            if ! test -x "$repo_tools"; then
              chmod +x "$repo_tools"
            fi
      - run:
          name: Build documentation.
          command: npm run docs
  sample_tests:
    docker:
      - image: 'node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5'
        user: node
    steps:
      - checkout
      - run: *remove_package_lock
      - run:
          name: Decrypt credentials.
          command: |
            openssl aes-256-cbc -d -in .circleci/key.json.enc \
                -out .circleci/key.json \
                -k "${SYSTEM_TESTS_ENCRYPTION_KEY}"
      - run:
          name: Install and link the module.
          command: |
            mkdir -p /home/node/.npm-global
            npm install
            repo_tools="node_modules/@google-cloud/nodejs-repo-tools/bin/tools"
            if ! test -x "$repo_tools"; then
              chmod +x "$repo_tools"
            fi
            npm link
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Link the module being tested to the samples.
          command: |
            cd samples/
            npm link dialogflow
            npm install
            cd ..
          environment:
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Run sample tests.
          command: npm run samples-test
          environment:
            GCLOUD_PROJECT: long-door-651
            GOOGLE_APPLICATION_CREDENTIALS: /home/node/dialogflow-samples/.circleci/key.json
            NPM_CONFIG_PREFIX: /home/node/.npm-global
      - run:
          name: Remove unencrypted key.
          command: rm .circleci/key.json
          when: always
    working_directory: /home/node/dialogflow-samples
  publish_npm:
    docker:
      - image: 'node:8@sha256:a4c4106ddda19c2c228cbdfbc0f0d7a5f27c383b0486f88fc2c2c40153763cf5'
        user: node
    steps:
      - checkout
      - run:
          name: Set NPM authentication.
          command: 'echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc'
      - run:
          name: Publish the module to npm.
          command: npm publish
